[local_hosts]
local ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[remote_containers]
target-a ansible_host=80.48.37.162 ansible_user=root

[managed_hosts:children]
local_hosts
remote_containers

[remote_containers:vars]
ansible_port=18888
ansible_ssh_private_key_file=./ssh/id_ed25519
ansible_become=false
use_become=false
ansible_python_interpreter=/usr/bin/python3
